.TH hmtimer 1 "February 2019" "version 3.0.2"
.SH NAME
hmtimer \- A graphical shutdown timer
.SH SYNOPSIS
.B hmtimer
[\-t time] [\-m] [\-a ACTION] [\-\-help] [\-\-version]
.SH DESCRIPTION
.B hmtimer
is a graphical shutdown timer for Linux and Windows.
It enables you to shutdown, turn off monitor, reboot or play sound after a period of time.
.SH OPTIONS
.TP
\fB\-t SECONDS\fR
set time in seconds and start timer
.TP
\fB\-m\fR
minimize to tray
.TP
\fB\-a ACTION\fR
set action when time is up.
.br
available actions: nothing, monitor, shutdown, reboot, sound, runprogram
.TP
\fB\-\-help\fR
display help and exit
.TP
\fB\-\-version\fR
display version and exit
