######################################################################
# Automatically generated by qmake (3.0) ??? ?? 16 15:15:20 2014
######################################################################

TEMPLATE = subdirs
SUBDIRS=hmtimer

install_desktop.files=hmtimer.desktop
install_desktop.path=/usr/share/applications
INSTALLS+=install_desktop
